name: Publish log
on: push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
      - name: Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SERVER }}
          remote-user: ${{ secrets.USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.PATH }}
          source-path: ${{ github.workspace }}/_site/
          rsync-options: --dry-run  --verbose --progress --human-readable --exclude=node_modules* --exclude=.git*  --exclude=.gitignore
